ignoreClassNames: [com.liferay.portal.repository.liferayrepository.model.LiferayFileEntry, com.liferay.portal.kernel.model.Repository, com.liferay.portal.kernel.repository.model.FileEntry, com.liferay.portal.kernel.repository.model.Folder, com.liferay.portal.kernel.model.UserPersonalSite]
modelInfo: [{
    model: default,
    queryHelperClass: !!jorgediazest.stagingchecker.model.StagingCheckerQueryHelper {},
    filter: "",
    attributesToQuery: [pk,uuid,companyId,groupId,classPK,classNameId,createDate,status,version,name,title,description,size],
    exactAttributesToCheck: [createDate,status,version,name,title,description,size,AssetTag.uuid,AssetCategory.uuid,com.liferay.portal.kernel.model.ResourcePermission],
    relatedDataToQuery: [
        {model: com.liferay.portal.kernel.model.ResourcePermission, mappingsSource: [pk], mappingsRelated: [primKey], attributesToQuery: [roleId,ownerId,actionIds], raw: true},
        {model: com.liferay.portal.kernel.model.ResourceBlockPermission, mappingsSource: [resourceBlockId], mappingsRelated: [resourceBlockId], attributesToQuery: [roleId,actionIds], raw: true},
        {model: com.liferay.asset.kernel.model.AssetEntry,  mappingsSource: [pk], mappingsRelated: [classPK], attributesToQuery: [AssetEntry.entryId,AssetEntries_AssetCategories.categoryId,AssetEntries_AssetTags.tagId,AssetEntry.priority,AssetEntry.visible]},
        {model: com.liferay.asset.kernel.model.AssetCategory, mappingsSource: [AssetEntries_AssetCategories.categoryId], mappingsRelated: [AssetCategory.categoryId], attributesToQuery: [AssetCategory.uuid]},
        {model: com.liferay.asset.kernel.model.AssetTag, mappingsSource: [AssetEntries_AssetTags.tagId],  mappingsRelated: [AssetTag.tagId], attributesToQuery: [AssetTag.uuid]}
    ],
    keyAttributes: [uuid]
},
{
    model: workflowedModel
},
{
    model: resourcedModel,
    attributesToQuery: [pk,uuid,companyId,groupId,classPK,classNameId,createDate,status,version,name,title,description,size,resourcePrimKey],
    relatedDataToQuery: [
        {model: com.liferay.portal.kernel.model.ResourcePermission, mappingsSource: [resourcePrimKey], mappingsRelated: [primKey], attributesToQuery: [roleId,ownerId,actionIds], raw: true},
        {model: com.liferay.asset.kernel.model.AssetEntry,  mappingsSource: [resourcePrimKey], mappingsRelated: [classPK], attributesToQuery: [AssetEntry.entryId,AssetEntries_AssetCategories.categoryId,AssetEntries_AssetTags.tagId,AssetEntry.priority,AssetEntry.visible]},
        {model: com.liferay.asset.kernel.model.AssetCategory, mappingsSource: [AssetEntries_AssetCategories.categoryId], mappingsRelated: [AssetCategory.categoryId], attributesToQuery: [AssetCategory.uuid]},
        {model: com.liferay.asset.kernel.model.AssetTag, mappingsSource: [AssetEntries_AssetTags.tagId],  mappingsRelated: [AssetTag.tagId], attributesToQuery: [AssetTag.uuid]}
    ],
},
{
    model: com.liferay.asset.kernel.model.AssetCategory,
    exactAttributesToCheck: [status,version,name,title,description,size,AssetTag.uuid,AssetCategory.uuid,com.liferay.portal.kernel.model.ResourcePermission]
},
{
    model: com.liferay.asset.kernel.model.AssetVocabulary,
    exactAttributesToCheck: [status,version,name,title,description,size,AssetTag.uuid,AssetCategory.uuid,com.liferay.portal.kernel.model.ResourcePermission]
},
{
    model: com.liferay.journal.model.JournalArticle,
    filter: "classNameId=0",
    exactAttributesToCheck: [status,version,name,title,description,size,AssetTag.uuid,AssetCategory.uuid,com.liferay.portal.kernel.model.ResourcePermission],
    relatedDataToQuery: [
        {model: com.liferay.portal.kernel.model.ResourcePermission, mappingsSource: [resourcePrimKey], mappingsRelated: [primKey], attributesToQuery: [roleId,ownerId,actionIds], raw: true},
        {model: com.liferay.asset.kernel.model.AssetEntry,  mappingsSource: [resourcePrimKey], mappingsRelated: [classPK], attributesToQuery: [AssetEntry.entryId,AssetEntries_AssetCategories.categoryId,AssetEntries_AssetTags.tagId,AssetEntry.priority,AssetEntry.visible]},
        {model: com.liferay.asset.kernel.model.AssetCategory, mappingsSource: [AssetEntries_AssetCategories.categoryId], mappingsRelated: [AssetCategory.categoryId], attributesToQuery: [AssetCategory.uuid]},
        {model: com.liferay.asset.kernel.model.AssetTag, mappingsSource: [AssetEntries_AssetTags.tagId],  mappingsRelated: [AssetTag.tagId], attributesToQuery: [AssetTag.uuid]},
        {model: com.liferay.journal.model.JournalArticleResource, mappingsSource: [resourcePrimKey],  mappingsRelated: [resourcePrimKey], attributesToQuery: [JournalArticleResource.uuid]}
    ],
    keyAttributes: [JournalArticleResource.uuid,version],
},
{
    model: com.liferay.document.library.kernel.model.DLFileEntry,
    filter: "groupId=repositoryId and classNameId=0",
    exactAttributesToCheck: [createDate,status,version,title,description,size,AssetTag.uuid,AssetCategory.uuid,com.liferay.portal.kernel.model.ResourcePermission]
},
{
    model: com.liferay.document.library.kernel.model.DLFolder,
    filter: "groupId=repositoryId"
},
{
    model: com.liferay.document.library.kernel.model.DLFileShortcut,
    filter: "groupId=repositoryId"
},
{
    model: com.liferay.document.library.kernel.model.DLFileVersion,
    filter: "groupId=repositoryId"
},
{
    model: "com.liferay.message.boards.kernel.model.MBMessage",
    filter: "classNameId=0"
}]

#Configuration to retrieve remote configuration
remoteConfigurationBackup: {62: {}, 70: {}}
remoteConfigurationUrl: "https://gist.githubusercontent.com/jorgediaz-lr/92d813db194ffc6590920def353c3768/raw/staging-checker_configuration.yml"
remoteConfigurationTimeoutMilis: 86400000

#Configuration to show offline update message
offlineUpdateMessage: 'Your Staging Checker version is more than six month old!! Download a new version: <a href="https://web.liferay.com/es/marketplace/-/mp/application/70121999">https://web.liferay.com/es/marketplace/-/mp/application/70121999</a>'
offlineUpdateTimeoutMilis: 15552000000